// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.178.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Azure.Domain
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Globalization;
    using global::System.Linq;

    using global::Naos.Database.Domain;

    using global::OBeautifulCode.Cloning.Recipes;
    using global::OBeautifulCode.Equality.Recipes;
    using global::OBeautifulCode.Type;
    using global::OBeautifulCode.Type.Recipes;

    using static global::System.FormattableString;

    [Serializable]
    public partial class ConnectionStringBlobContainerResourceLocator : IModel<ConnectionStringBlobContainerResourceLocator>
    {
        /// <summary>
        /// Determines whether two objects of type <see cref="ConnectionStringBlobContainerResourceLocator"/> are equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are equal; otherwise false.</returns>
        public static bool operator ==(ConnectionStringBlobContainerResourceLocator left, ConnectionStringBlobContainerResourceLocator right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
            {
                return false;
            }

            var result = left.Equals(right);

            return result;
        }

        /// <summary>
        /// Determines whether two objects of type <see cref="ConnectionStringBlobContainerResourceLocator"/> are not equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are not equal; otherwise false.</returns>
        public static bool operator !=(ConnectionStringBlobContainerResourceLocator left, ConnectionStringBlobContainerResourceLocator right) => !(left == right);

        /// <inheritdoc />
        public bool Equals(ConnectionStringBlobContainerResourceLocator other)
        {
            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (ReferenceEquals(other, null))
            {
                return false;
            }

            var result = this.ContainerName.IsEqualTo(other.ContainerName, StringComparer.Ordinal)
                      && this.ConnectionString.IsEqualTo(other.ConnectionString, StringComparer.Ordinal)
                      && this.Timeout.IsEqualTo(other.Timeout);

            return result;
        }

        /// <inheritdoc />
        public override bool Equals(object obj) => this == (obj as ConnectionStringBlobContainerResourceLocator);

        /// <inheritdoc />
        public override int GetHashCode() => HashCodeHelper.Initialize()
            .Hash(this.ContainerName)
            .Hash(this.ConnectionString)
            .Hash(this.Timeout)
            .Value;

        /// <inheritdoc />
        public new ConnectionStringBlobContainerResourceLocator DeepClone() => (ConnectionStringBlobContainerResourceLocator)this.DeepCloneInternal();

        /// <summary>
        /// Deep clones this object with a new <see cref="ContainerName" />.
        /// </summary>
        /// <param name="containerName">The new <see cref="ContainerName" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ConnectionStringBlobContainerResourceLocator" /> using the specified <paramref name="containerName" /> for <see cref="ContainerName" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ConnectionStringBlobContainerResourceLocator DeepCloneWithContainerName(string containerName)
        {
            var result = new ConnectionStringBlobContainerResourceLocator(
                                 containerName,
                                 this.ConnectionString?.DeepClone(),
                                 this.Timeout.DeepClone());

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="ConnectionString" />.
        /// </summary>
        /// <param name="connectionString">The new <see cref="ConnectionString" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ConnectionStringBlobContainerResourceLocator" /> using the specified <paramref name="connectionString" /> for <see cref="ConnectionString" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ConnectionStringBlobContainerResourceLocator DeepCloneWithConnectionString(string connectionString)
        {
            var result = new ConnectionStringBlobContainerResourceLocator(
                                 this.ContainerName?.DeepClone(),
                                 connectionString,
                                 this.Timeout.DeepClone());

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Timeout" />.
        /// </summary>
        /// <param name="timeout">The new <see cref="Timeout" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ConnectionStringBlobContainerResourceLocator" /> using the specified <paramref name="timeout" /> for <see cref="Timeout" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ConnectionStringBlobContainerResourceLocator DeepCloneWithTimeout(TimeSpan timeout)
        {
            var result = new ConnectionStringBlobContainerResourceLocator(
                                 this.ContainerName?.DeepClone(),
                                 this.ConnectionString?.DeepClone(),
                                 timeout);

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        protected override ResourceLocatorBase DeepCloneInternal()
        {
            var result = new ConnectionStringBlobContainerResourceLocator(
                                 this.ContainerName?.DeepClone(),
                                 this.ConnectionString?.DeepClone(),
                                 this.Timeout.DeepClone());

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        public override string ToString()
        {
            var result = Invariant($"Naos.Azure.Domain.ConnectionStringBlobContainerResourceLocator: ContainerName = {this.ContainerName?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, ConnectionString = {this.ConnectionString?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Timeout = {this.Timeout.ToString() ?? "<null>"}.");

            return result;
        }
    }
}